COQUTIL_TEST_DIR := $(patsubst %/,%,$(dir $(lastword $(MAKEFILE_LIST))))
COQUTIL_TEST_VFILES := $(call rwildcard,$(COQUTIL_TEST_DIR),*.v)
COQUTIL_TEST_COQDEPFLAGS := -Q $(COQUTIL_TEST_DIR) $(notdir $(COQUTIL_TEST_DIR))
#COQUTIL_TEST_REQUIREFLAGS := -Q $(O)/$(COQUTIL_TEST_DIR) $(notdir $(COQUTIL_TEST_DIR))

COQUTIL_TEST_COQFLAGS := $(COQUTIL_REQUIREFLAGS) -w -deprecated-from-Coq,-deprecated-since-9.0,-deprecated-since-8.20
$(O)/$(COQUTIL_TEST_DIR)/%.vo: private COQFLAGS += $(COQUTIL_TEST_COQFLAGS)
$(O)/$(COQUTIL_TEST_DIR)/%.vos: private COQFLAGS += $(COQUTIL_TEST_COQFLAGS)
$(O)/$(COQUTIL_TEST_DIR)/%.vok: private COQFLAGS += $(COQUTIL_TEST_COQFLAGS)
$(COQUTIL_DIR)/_CoqProject: private COQFLAGS += $(COQUTIL_COQFLAGS)
