name: Update tested branch

on:
  workflow_dispatch:
  schedule:
    # run at 06:59 UTC each day
    - cron:  '59 6 * * *'

jobs:
  updateBranch:
    runs-on: ubuntu-latest
    name: Update tested
    steps:
    - uses: actions/checkout@v4
      with:
        ref: 'tested'
        fetch-depth: 0
    - run: pwd
    - uses: samuelgruetter/check-ci-success@master
      with:
        repo_owner: 'mit-plv'
        repo_name: 'coqutil'
        branch_name: 'master'
        check_name: 'master'
        github_token: ${{ secrets.GITHUB_TOKEN }}
    - uses: samuelgruetter/check-ci-success@master
      with:
        repo_owner: 'mit-plv'
        repo_name: 'coqutil'
        branch_name: 'master'
        check_name: 'v8.15'
        github_token: ${{ secrets.GITHUB_TOKEN }}
    - uses: samuelgruetter/check-ci-success@master
      with:
        repo_owner: 'mit-plv'
        repo_name: 'coqutil'
        branch_name: 'master'
        check_name: 'Ubuntu LTS'
        github_token: ${{ secrets.GITHUB_TOKEN }}
    - run: echo "This step runs after the python script"
    - run: git fetch origin master
    - run: git log --oneline --max-count=10
    - run: git merge --ff-only remotes/origin/master
    - run: git log --oneline --max-count=10
    - run: git push
