name: Update tested branch

on:
  schedule:
    # run at 06:59 UTC each day
    - cron:  '59 6 * * *'

jobs:
  updateBranch:
    runs-on: ubuntu-latest
    name: Update tested
    steps:
    - uses: actions/checkout@v2
      with:
        ref: 'tested'
        fetch-depth: 0
    - run: pwd
    - uses: samuelgruetter/check-ci-success@master
      with:
        repo_owner: 'mit-plv'
        repo_name: 'coqutil'
        branch_name: 'master'
        check_name: 'master'
    - uses: samuelgruetter/check-ci-success@master
      with:
        repo_owner: 'mit-plv'
        repo_name: 'coqutil'
        branch_name: 'master'
        check_name: '8.14.0'
    - uses: samuelgruetter/check-ci-success@master
      with:
        repo_owner: 'mit-plv'
        repo_name: 'coqutil'
        branch_name: 'master'
        check_name: '8.13.1'
    - uses: samuelgruetter/check-ci-success@master
      with:
        repo_owner: 'mit-plv'
        repo_name: 'coqutil'
        branch_name: 'master'
        check_name: '8.12.2'
    - uses: samuelgruetter/check-ci-success@master
      with:
        repo_owner: 'mit-plv'
        repo_name: 'coqutil'
        branch_name: 'master'
        check_name: '8.11.2'
    - uses: samuelgruetter/check-ci-success@master
      with:
        repo_owner: 'mit-plv'
        repo_name: 'coqutil'
        branch_name: 'master'
        check_name: 'Ubuntu LTS'
    - run: echo "This step runs after the python script"
    - run: git fetch origin master
    - run: git log --oneline --max-count=10
    - run: git merge --ff-only remotes/origin/master
    - run: git log --oneline --max-count=10
    - run: git push
